/********************************************************************************* 
* Ephesoft is a Intelligent Document Capture and Mailroom Automation program 
* developed by Ephesoft, Inc. Copyright (C) 2010-2011 Ephesoft Inc. 
* 
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Affero General Public License version 3 as published by the 
* Free Software Foundation with the addition of the following permission added 
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK 
* IN WHICH THE COPYRIGHT IS OWNED BY EPHESOFT, EPHESOFT DISCLAIMS THE WARRANTY 
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. 
* 
* This program is distributed in the hope that it will be useful, but WITHOUT 
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more 
* details. 
* 
* You should have received a copy of the GNU Affero General Public License along with 
* this program; if not, see http://www.gnu.org/licenses or write to the Free 
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
* 02110-1301 USA. 
* 
* You can contact Ephesoft, Inc. headquarters at 111 Academy Way, 
* Irvine, CA 92617, USA. or at email address info@ephesoft.com. 
* 
* The interactive user interfaces in modified source and object code versions 
* of this program must display Appropriate Legal Notices, as required under 
* Section 5 of the GNU Affero General Public License version 3. 
* 
* In accordance with Section 7(b) of the GNU Affero General Public License version 3, 
* these Appropriate Legal Notices must retain the display of the "Ephesoft" logo. 
* If the display of the logo is not reasonably feasible for 
* technical reasons, the Appropriate Legal Notices must display the words 
* "Powered by Ephesoft". 
********************************************************************************/ 

package com.ephesoft.dcma.batch.service;

import java.io.File;
import java.io.InputStream;
import java.io.Serializable;
import java.net.URL;
import java.util.List;

import com.ephesoft.dcma.batch.schema.Batch;
import com.ephesoft.dcma.batch.schema.HocrPages;
import com.ephesoft.dcma.batch.schema.Document.DocumentLevelFields;
import com.ephesoft.dcma.batch.schema.HocrPages.HocrPage;
import com.ephesoft.dcma.core.DCMAException;
import com.ephesoft.dcma.core.common.DCMABusinessException;
import com.ephesoft.dcma.core.exception.DCMAApplicationException;
import com.ephesoft.dcma.da.domain.BatchClassModule;
import com.ephesoft.dcma.da.id.BatchClassID;
import com.ephesoft.dcma.da.id.BatchInstanceID;

/**
 * This is a service to read and write data required by Batch Schema. Api's are present to move, rearrange, delete, create, swap the
 * document and pages from one to each other. On the basis of batch instance id and base folder location will read the batch.xml file
 * and rearrange the attribute of the xml file.
 * 
 * @author Ephesoft
 * @version 1.0
 * @see com.ephesoft.dcma.batch.service.BatchSchemaServiceImpl
 */
public interface BatchSchemaService {

	/**
	 * An api to generate the xml file for all the htmls generated by image process plug-ins.
	 * 
	 * @return batchInstanceIdentifier {@link String}
	 * @throws DCMAException If any error occurs.
	 */
	void htmlToXmlGeneration(String batchInstanceIdentifier) throws DCMAException;

	/**
	 * An api to generate the xml file for all the htmls generated by image process plug-ins.
	 * 
	 * @return batchInstanceIdentifier {@link String}
	 * @throws DCMAException If any error occurs.
	 * @throws DCMABusinessException
	 * @throws DCMAApplicationException
	 */
	void htmlToXmlGeneration(final BatchInstanceID batchInstanceID, final String pluginWorkflow) throws DCMAException;

	/**
	 * An api to get recostar project files for document type and batch class identifier.
	 * 
	 * @param batchClassIdentifier {@link String}
	 * @param documentType {@link String}
	 * @return List<String>
	 * @throws DCMAException
	 */
	List<String> getProjectFilesForDocumentType(String batchClassIdentifier, String documentType) throws DCMAException;

	/**
	 * An api to get the absolute path of the directory. It will create the directory if it is not exits and createDir boolean is true
	 * otherwise not.
	 * 
	 * @param batchClassIdentifier {@link String}
	 * @param directoryName {@link String}
	 * @param createDir boolean
	 * @return absolute path of the directory.
	 */
	String getAbsolutePath(String batchClassIdentifier, String directoryName, boolean createDir);

	/**
	 * An api to return the complete local folder location path.
	 * 
	 * @return {@link String} localFolderLocation
	 */
	String getLocalFolderLocation();

	/**
	 * Script folder name.
	 * 
	 * @return {@link String} script folder name.
	 */
	String getScriptFolderName();

	/**
	 * Cmis plugin mapping folder name.
	 * 
	 * @return {@link String} cmis plugin mapping folder name.
	 */
	String getCmisPluginMappingFolderName();

	/**
	 * An api to return the sample path for search classification.
	 * 
	 * @param batchClassIdentifier {@link String}
	 * @param createDir boolean
	 * @return {@link String} searchClassSamplePath
	 */
	String getSearchClassSamplePath(String batchClassIdentifier, boolean createDir);

	/**
	 * An api to return the index folder for search classification.
	 * 
	 * @param batchClassIdentifier {@link String}
	 * @param createDir boolean
	 * @return {@link String} searchClassSamplePath
	 */
	String getSearchClassIndexFolder(String batchClassIdentifier, boolean createDir);

	/**
	 * An api to return the base folder path for imagemagick.
	 * 
	 * @param batchClassIdentifier {@link String}
	 * @param createDir boolean
	 * @return {@link String} searchClassSamplePath
	 */
	String getImageMagickBaseFolderPath(String batchClassIdentifier, boolean createDir);

	/**
	 * An api to return the Index folder for fuzzy db.
	 * 
	 * @param batchClassIdentifier {@link String}
	 * @param createDir boolean
	 * @return {@link String} searchClassSamplePath
	 */
	String getFuzzyDBIndexFolder(String batchClassIdentifier, boolean createDir);

	/**
	 * An api to return the complete export folder location path.
	 * 
	 * @return {@link String} exportFolderLocation.
	 */
	String getExportFolderLocation();

	/**
	 * An api to return the base http url path.
	 * 
	 * @return {@link String} base http url path.
	 */
	String getBaseHttpURL();

	/**
	 * An api to create the hocrPages object.
	 * 
	 * @param batch {@link Batch}
	 * @param batchInstanceIdentifier {@link {@link String}}
	 * @param pageId {@link {@link String}}
	 */
	public void createHocr(HocrPages hocrPages, String batchInstanceIdentifier, String pageId);

	/**
	 * An api to get the HocrPages object for an input of HOCR.XML.
	 * 
	 * @param batchInstanceIdentifier Serializable
	 * @param pageId {@link {@link String}}
	 * @return {@link HocrPages}
	 */
	HocrPages getHocrPages(Serializable batchInstanceIdentifier, String pageId);

	/**
	 * An api to get the Batch object for an input of batchInstanceIdentifier.
	 * 
	 * @param batchInstanceIdentifier Serializable
	 * @return
	 */
	Batch getBatch(Serializable batchInstanceIdentifier);

	/**
	 * An api to create the Batch object.
	 * 
	 * @param batch Batch
	 */
	void createBatch(Batch batch);

	/**
	 * An api to update the Batch object.
	 * 
	 * @param batch Batch
	 */
	void updateBatch(Batch batch);

	/**
	 * An api to fetch BatchClass by id.
	 * 
	 * @param id Serializable
	 * @param files File[]
	 */
	void storeFiles(Serializable id, File[] files);

	/**
	 * @param id Serializable
	 * @param files File[]
	 */
	void backUpFiles(Serializable id, File[] files);

	/**
	 * An api to get the URL object for the specified file name.
	 * 
	 * @param batchInstanceIdentifier {@link String}
	 * @param fileName {@link String}
	 * @return URL object.
	 */
	URL getURL(String batchInstanceIdentifier, String fileName);

	/**
	 * An api to get the URL object for the batch ID.
	 * 
	 * @param batchInstanceIdentifier {@link String}
	 * @return URL object.
	 */
	URL getBatchContextURL(String batchInstanceIdentifier);

	/**
	 * An api to get the File object for the specified file name.
	 * 
	 * @param batchInstanceIdentifier {@link String}
	 * @param fileName {@link String}
	 * @return File object.
	 */
	File getFile(String batchInstanceIdentifier, String fileName);

	/**
	 * An api to get the input stream object for the specified file name.
	 * 
	 * @param batchInstanceIdentifier {@link String}
	 * @param fileName {@link String}
	 * @return InputStream object.
	 */
	InputStream getInputStream(String batchInstanceIdentifier, String fileName);

	/**
	 * An api to merge two different documents to a single document. This will merge all the pages of second document to first
	 * document.
	 * 
	 * @param batchInstanceIdentifier {@link String}
	 * @param docIDOne {@link String}
	 * @param mergeDocID {@link String}
	 * @throws DCMAApplicationException If any of the input parameter is null.
	 */
	Batch mergeDocuments(String batchInstanceIdentifier, String docIDOne, String mergeDocID) throws DCMAApplicationException;

	/**
	 * An api to swap one page of one document to second page of other document.
	 * 
	 * @param batchInstanceIdentifier {@link String}
	 * @param swapDocIDOne {@link String}
	 * @param swapPageIDOne {@link String}
	 * @param swapDocIDTwo {@link String}
	 * @param swapPageIDTwo {@link String}
	 * @throws DCMAApplicationException If not able to find swapDocIDOne, swapPageIDOne, swapDocIDTwo or swapPageIDTwo. If not able to
	 *             find all swapPageIDOne and swapPageIDTwo within swapDocIDOne and swapDocIDTwo respectively.
	 */
	void swapPageOfDocuments(String batchInstanceIdentifier, String swapDocIDOne, String swapPageIDOne, String swapDocIDTwo,
			String swapPageIDTwo) throws DCMAApplicationException;

	/**
	 * An api to swap pages of document. This will swap the pages for the input document id.
	 * 
	 * @param batchInstanceIdentifier {@link String}
	 * @param docID {@link String}
	 * @param swapPageIDOne {@link String}
	 * @param swapPageIDTwo {@link String}
	 * @throws DCMAApplicationException If not able to find docID, swapPageIDOne or swapPageIDTwo. If not able to find all
	 *             swapPageIDOne and swapPageIDTwo within docID.
	 */
	void swapPageOfDocument(String batchInstanceIdentifier, String docID, String swapPageIDOne, String swapPageIDTwo)
			throws DCMAApplicationException;

	/**
	 * An api to split the document for given input page id. This will create a new document starting from input page id to the last
	 * page id.
	 * 
	 * @param batchInstanceIdentifier String
	 * @param docID String
	 * @param pageID String
	 * @throws DCMAApplicationException If any one of the parameter is null or pageID is not present in docID.
	 */
	void splitDocument(String batchInstanceIdentifier, String docID, String pageID) throws DCMAApplicationException;

	/**
	 * An api to re order pages of document. This will re order the pages for the input document id.
	 * 
	 * @param batchInstanceIdentifier String
	 * @param docID String
	 * @param reOrderOfPageIDs String
	 * @throws DCMAApplicationException If not able to find docID, reOrderOfPageIDs. If not able to find all reOrderOfPageIDs within
	 *             duplicatePageID.
	 */
	void reOrderPagesOfDocument(String batchInstanceIdentifier, String docID, List<String> reOrderOfPageIDs)
			throws DCMAApplicationException;

	/**
	 * An api to create duplicate page of document. This will create duplicate for all the information available to page. This will
	 * create duplicate for all the files present at page level fields.
	 * 
	 * @param batchInstanceIdentifier String
	 * @param docID String
	 * @param duplicatePageID String
	 * @throws DCMAApplicationException If not able to find docID, duplicatePageID. If not able to find removePageID within
	 *             duplicatePageID.
	 */
	void duplicatePageOfDocument(String batchInstanceIdentifier, String docID, String duplicatePageID) throws DCMAApplicationException;

	/**
	 * An api to remove the page of document. This will remove all the information available to page. This will delete all the files
	 * present at page level fields. If a document have single page and we are deleting that page means delete the whole document.
	 * 
	 * @param batchInstanceIdentifier String
	 * @param docID String
	 * @param removePageID String
	 * @throws DCMAApplicationException If not able to find docID, removePageID. If not able to find removePageID within docID.
	 */
	void removePageOfDocument(String batchInstanceIdentifier, String docID, String removePageID) throws DCMAApplicationException;

	/**
	 * An api to move the page of one document to to another document. Position of the page in new document will depend on the to page
	 * ID. If the isAfterToPageID boolean is true then from page ID is added after the to page ID other wise before the to page ID.
	 * After the movement api will delete the from page ID from the from doc ID.
	 * 
	 * @param batchInstanceIdentifier String
	 * @param fromDocID String
	 * @param fromPageID String
	 * @param toDocID String
	 * @param toPageID String from page ID position relative to this page ID.
	 * @param isAfterToPageID boolean true means add after the to page ID. false means add before the to page ID.
	 * @throws DCMAApplicationException If not able to find fromDocID, fromPageID or toDocID. If not able to find fromPageID within
	 *             fromDocID.
	 */
	void movePageOfDocument(String batchInstanceIdentifier, String fromDocID, String fromPageID, String toDocID, String toPageID,
			boolean isAfterToPageID) throws DCMAApplicationException;

	/**
	 * An api to update the document type name and document level fields for the input doc type ID.
	 * 
	 * @param batchInstanceIdentifier String
	 * @param docID String
	 * @param docTypeName String
	 * @param documentLevelFields DocumentLevelFields
	 * @throws DCMAApplicationException If any one of the parameter is null or docID is not present in batch.
	 */
	void updateDocTypeName(String batchInstanceIdentifier, String docID, String docTypeName, DocumentLevelFields documentLevelFields)
			throws DCMAApplicationException;

	/**
	 * An api which will return true if the review is required other wise false.
	 * 
	 * @param batchInstanceIdentifier String
	 * @return boolean true if isReviewRequired other wise false.
	 * @throws DCMAApplicationException If any of the parameter is not valid.
	 */
	boolean isReviewRequired(final String batchInstanceIdentifier) throws DCMAApplicationException;

	/**
	 * An api which will return true if the review is required other wise false.
	 * 
	 * @param batchInstanceIdentifier String
	 * @return boolean true if isReviewRequired other wise false.
	 * @throws DCMAApplicationException If any of the parameter is not valid.
	 */
	boolean isReviewRequired(final String batchInstanceIdentifier, boolean checkReviewFlag) throws DCMAApplicationException;

	/**
	 * An api which will return true if the validation is required for the document level fields other wise false.
	 * 
	 * @param batchInstanceIdentifier String
	 * @return boolean true if isValidationRequired other wise false.
	 * @throws DCMAApplicationException If any of the parameter is not valid.
	 */
	boolean isValidationRequired(final String batchInstanceIdentifier) throws DCMAApplicationException;

	/**
	 * An api to generate all the folder structure for samples.
	 * 
	 * @param batchClassIDList List<List<String>>
	 * @throws DCMAApplicationException If any of the parameter is not valid.
	 */
	void sampleGeneration(final List<List<String>> batchIdDocPgNameList) throws DCMAApplicationException;

	/**
	 *An api to delete the folders.
	 * 
	 * @param docTypeNameList the list of name of folders that have been deleted
	 * @param batchClassIdentifier the batch class name from which the folders are deleted
	 * @throws DCMAApplicationException if any of the parameter is not valid
	 */
	void deleteDocTypeFolder(List<String> docTypeNameList, String batchClassIdentifier) throws DCMAApplicationException;

	public String getThumbnailFilePath(String batchInstanceIdentifier, String documentId, String pageId)
			throws DCMAApplicationException;

	public String getDisplayImageFilePath(String batchInstanceIdentifier, String documentId, String pageId)
			throws DCMAApplicationException;

	/**
	 * An Api to fetch the image URL's excluding the imagename
	 * 
	 * @return the URL to be appended to the image name.
	 */
	public String getWebScannerScannedImagesURL();

	/**
	 * An Api to fetch the folder in which the scanned images are being kept.
	 * 
	 * @return the scanned images folder path.
	 */
	public String getWebScannerScannedImagesFolderPath();

	/**
	 * API to get the base folder path.
	 * 
	 * @return base folder absolute path.
	 */
	public String getBaseSampleFDLock();

	/**
	 * Api to create a temp folder for scanned images for the given name
	 * 
	 */
	public void createWebScannerFolder(String folderName) throws DCMAApplicationException;

	/**
	 * API to copy all the .tiff and .tif files from the sourcePath+folderName to the batchPath+folderName
	 * 
	 * @param sourcePath the path containing the folder to be copied
	 * @param folderName the folder to be copied.
	 * @param batchId the identifier of batch to which the batch is to be copied
	 */
	public void copyFolder(String sourcePath, String folderName, String batchClassID) throws DCMAApplicationException;

	/**
	 * Api to return base folder location
	 * 
	 */
	public String getBaseFolderLocation();

	/**
	 * An api to fetch project File Base Folder location.
	 * 
	 * @return String
	 */
	public String getProjectFileBaseFolder();

	/**
	 * An api to fetch Email Base Folder location using Http protocol.
	 * 
	 * @return String
	 */
	public String getHttpEmailFolderPath();

	/**
	 * An api to fetch Batches Folder location.
	 * 
	 * @return String
	 */
	public String getBatchFolderURL();

	/**
	 * An api to fetch Email Base Folder location.
	 * 
	 * @return String
	 */
	public String getEmailFolderPath();

	/**
	 * Api to get test kv extraction folder path.
	 * 
	 * @param batchClassID
	 * @param createDirectory
	 * @return absolute folder location
	 */
	public String getTestKVExtractionFolderPath(BatchClassID batchClassID, boolean createDirectory);

	/**
	 * This api is used to generate the HocrPage object for input hocr file.
	 * 
	 * @param pageName {@link String}
	 * @param pathOfHOCRFile {@link String}
	 * @param outputFilePath {@link String}
	 * @param batchClassIdentifier 
	 * @return {@link HocrPage}
	 */
	public HocrPage generateHocrPage(String pageName, String pathOfHOCRFile, String outputFilePath, String batchClassIdentifier);

	/**
	 * An api to return the complete export batch class folder location path.
	 * 
	 * @return String Batch Export Folder Location
	 */
	public String getBatchExportFolderLocation();

	/**
	 * An api to return the Index folder name for fuzzy db.
	 * 
	 * @return String fuzzyDb Index Folder Path
	 */
	public String getFuzzyDBIndexFolderName();

	/**
	 * An api to return the Index folder name for fuzzy db.
	 * 
	 * @return String fuzzyDb Index Folder Path
	 */
	public String getImagemagickBaseFolderName();

	/**
	 * An api to return the Index folder name for fuzzy db.
	 * 
	 * @return String fuzzyDb Index Folder Path
	 */
	public String getSearchSampleName();

	/**
	 * An api to return the Index folder name for fuzzy db.
	 * 
	 * @return String fuzzyDb Index Folder Path
	 */
	public String getSearchIndexFolderName();

	/**
	 * An api to return the test kv_extraction sample folder name.
	 * 
	 * @return String test kv_extraction sample folder name
	 */

	public String getTestKVExtractionFolderName();

	/**
	 * 
	 * @return String name of batch Class Serializable Description as appearing on the UI
	 */

	public String getBatchClassSerializableFile();

	/**
	 * 
	 * @return String Name of filebound plugin mapping folder
	 */
	public String getFileboundPluginMappingFolderName();

	/**
	 * API to get the temp folder location for a batch class.
	 * 
	 * @return {@link String}
	 */
	public String getTempFolderName();

	/**
	 * API to copy all the files from the Email download folder to the UNC Folder.
	 * 
	 * @param sourcePath the path containing the folder to be copied
	 * @param folderName the folder to be copied.
	 * @param batchId the identifier of batch to which the batch is to be copied
	 */
	public void copyEmailFolderToUNC(String sourcePath, String folderName, String batchClassID) throws DCMAApplicationException;

	/**
	 * Api to get test table folder path.
	 * 
	 * @param batchClassID
	 * @param createDirectory
	 * @return absolute folder location
	 */
	public String getTestTableFolderPath(BatchClassID batchClassID, boolean createDirectory);

	/**
	 * An api to return the test table sample folder name.
	 * 
	 * @return String test table sample folder name
	 */

	public String getTestTableFolderName();

	/**
	 * API to create the batch XML at the end of the specified plugin
	 * 
	 * @param batchInstanceID
	 * @param pluginWorkflow
	 */
	public void backUpBatchXML(final BatchInstanceID batchInstanceID, final String pluginWorkflow);

	/**
	 * API to return the ValidationScriptName.
	 * 
	 * @return String ValidationScriptName
	 */
	public String getValidationScriptName();

	/**
	 * API to return the threadpool lock folder. This folder signifies if any thread is currently running for this batch instance at
	 * any point of time.
	 * 
	 * @return String thread pool lock folder name
	 */
	public String getThreadpoolLockFolderName();

	/**
	 * API to add new table.
	 * 
	 * @return String AddNewTableScriptName
	 */
	public String getAddNewTableScriptName();

	/**
	 * API to set local folder.
	 * 
	 * @param localFolderLocation
	 */
	public void setLocalFolderLocation(String localFolderLocation);

	/**
	 * API to set local folder.
	 * 
	 * @param testFolderLocation
	 */
	public void setTestFolderLocation(String testFolderLocation);

	/**
	 * API to return test folder.
	 * 
	 * @return String test folder name
	 */
	public String getTestFolderLocation();

	/**
	 * API to set base folder of the project.
	 * 
	 * @param baseFolderLocation
	 */
	public void setBaseFolderLocation(String baseFolderLocation);

	/**
	 * API to get the detached batch class module object for a batch class.
	 * 
	 * @param batchClassIdentifier {@link String}
	 * @param moduleName {@link String}
	 * @return {@link BatchClassModule}
	 */
	BatchClassModule getDetachedBatchClassModuleByName(String batchClassIdentifier, String moduleName);

	/**
	 * API to get Script Config Folder Name.
	 *
	 */
	public String getScriptConfigFolderName();

}
